# Generated by Django 5.2.8 on 2025-12-20 13:17

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_inventory', '0016_add_contracts'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contractassignment',
            name='uniq_supportassignment_asset_sku_period',
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='vendor_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(models.F('vendor'), django.db.models.functions.text.Lower('contract_id'), name='netbox_inventory_contract_unique_vendor_contract_id', violation_error_message='Contract must be unique per vendor.'),
        ),
        migrations.AddConstraint(
            model_name='contractassignment',
            constraint=models.UniqueConstraint(fields=('asset', 'sku', 'start_date', 'end_date'), name='uniq_contractassignment_asset_sku_period'),
        ),
        migrations.AlterConstraint(
            model_name='contractvendor',
            name='netbox_inventory_contractvendor_unique_name',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='netbox_inventory_contractvendor_unique_name', violation_error_message='Contract Vendor must be unique.'),
        ),
    ]
