# Generated by Django 5.2.8 on 2025-12-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory', '0017_remove_contractassignment_uniq_supportassignment_asset_sku_period_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='purchase_order_id',
            new_name='purchase_order',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='vendor_order_id',
            new_name='purchase_requisition',
        ),
        migrations.AddField(
            model_name='purchase',
            name='request_ticket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
