# Generated by Django 5.2.9 on 2025-12-24 12:02

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0216_latitude_longitude_validators'),
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_inventory', '0018_rename_purchase_order_id_purchase_purchase_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='delivery',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='request_ticket',
            new_name='internal_reference',
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='dcim.manufacturer')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='netbox_inventory.purchase')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['purchase', 'name'],
                'unique_together': {('purchase', 'name')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='asset',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='netbox_inventory.order'),
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
