# Generated by Django 5.2.9 on 2025-12-26 02:17

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_inventory', '0019_remove_asset_delivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareLifecycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('assigned_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('end_of_sale', models.DateField(blank=True, null=True)),
                ('end_of_maintenance', models.DateField(blank=True, null=True)),
                ('end_of_security', models.DateField(blank=True, null=True)),
                ('last_contract_attach', models.DateField(blank=True, null=True)),
                ('last_contract_renewal', models.DateField(blank=True, null=True)),
                ('end_of_support', models.DateField(blank=True, null=True)),
                ('notice_url', models.URLField(blank=True)),
                ('support_basis', models.CharField(default='support', max_length=16)),
                ('assigned_object_type', models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'dcim'), ('model__in', ('moduletype', 'devicetype'))), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['assigned_object_type'],
                'constraints': [models.UniqueConstraint(models.F('assigned_object_type'), models.F('assigned_object_id'), name='netbox_inventory_hardwarelifecycle_unique_object', violation_error_message='Objects must be unique.')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
