# Generated by Django 5.2.9 on 2025-12-29 03:53

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0216_latitude_longitude_validators'),
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_inventory', '0020_hardwarelifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_programs', to='dcim.manufacturer')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AssetProgramCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('eligibility', models.CharField(default='unknown', max_length=20)),
                ('effective_start', models.DateField(blank=True, null=True)),
                ('effective_end', models.DateField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('evidence_url', models.URLField(blank=True)),
                ('source', models.CharField(default='manual', max_length=20)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('activated_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_program_coverages', to='netbox_inventory.contract')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_coverages', to='netbox_inventory.asset')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_coverages', to='netbox_inventory.vendorprogram')),
            ],
            options={
                'ordering': ('program__name', 'asset__name'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('effective_end__isnull', True)), fields=('asset', 'program'), name='netboxinv_asset_program_coverage_one_current')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
