# Generated by Django 5.2.9 on 2025-12-30 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory', '0021_vendorprogram_assetprogramcoverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractassignment',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_assignments', to='netbox_inventory.vendorprogram'),
        ),
        migrations.AddField(
            model_name='contractsku',
            name='contract_type',
            field=models.CharField(default='support-ea', max_length=16),
            preserve_default=False,
        ),
    ]
