# Generated by Django 5.2.9 on 2025-12-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory', '0022_contractassignment_program_contractsku_contract_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetprogramcoverage',
            name='activated_contract',
        ),
        migrations.AddField(
            model_name='vendorprogram',
            name='contract_type',
            field=models.CharField(default='support-alc', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assetprogramcoverage',
            name='status',
            field=models.CharField(default='planned', max_length=20),
        ),
    ]
