# Generated by Django 5.2.9 on 2025-12-30 14:18

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0216_latitude_longitude_validators'),
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_inventory', '0023_remove_assetprogramcoverage_activated_contract_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vendorprogram',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'contract_type'), name='uniq_vendorprogram_manufacturer_contract_type', violation_error_message='A program already exists for this manufacturer and contract type.'),
        ),
        migrations.AddConstraint(
            model_name='vendorprogram',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('manufacturer'), name='uniq_vendorprogram_manufacturer_name_ci', violation_error_message='Program name must be unique per manufacturer.'),
        ),
    ]
