# Generated by Django 5.2.9 on 2026-01-01 03:28

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0216_latitude_longitude_validators'),
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_inventory', '0024_vendorprogram_uniq_vendorprogram_manufacturer_contract_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='base_license_source',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='asset',
            name='base_license_source_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='vendor_ship_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LicenseSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('license_kind', models.CharField(default='subscription', max_length=16)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_skus', to='dcim.manufacturer')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'License SKU',
                'verbose_name_plural': 'License SKUs',
                'ordering': ('manufacturer', 'sku'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='asset',
            name='base_license_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_as_base', to='netbox_inventory.licensesku'),
        ),
    ]
