# Generated by Django 5.2.9 on 2026-01-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory', '0025_asset_base_license_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='allocation_status',
            field=models.CharField(default='unallocated', max_length=30),
        ),
    ]
