# Generated by Django 5.2.9 on 2026-01-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory', '0026_asset_allocation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='base_license_source',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='base_license_source_ref',
        ),
        migrations.AddField(
            model_name='asset',
            name='disposal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='disposal_reason',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='disposal_reference',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
