# Generated by Django 5.2.9 on 2026-01-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory', '0027_remove_asset_base_license_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='allocation_status',
            field=models.CharField(default='unallocated', max_length=30, null=True),
        ),
    ]
