# Generated by Django 5.2.9 on 2026-01-11 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0216_latitude_longitude_validators'),
        ('netbox_inventory', '0028_alter_asset_allocation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='installed_site_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_with_installed_site_override', to='dcim.site'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='allocation_status',
            field=models.CharField(blank=True, default='unallocated', max_length=30, null=True),
        ),
    ]
