# Generated by Django 5.2.9 on 2026-01-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory', '0029_asset_installed_site_override_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='allocation_status',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
