# Generated by Django 5.2.9 on 2026-01-13 12:37

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0216_latitude_longitude_validators'),
        ('netbox_inventory', '0030_alter_asset_allocation_status'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwarelifecycle',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, through='taggit.TaggedItem', to='taggit.Tag'),
        ),
        migrations.AlterField(
            model_name='order',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_manufacturer', to='dcim.manufacturer'),
        ),
    ]
