# Generated by Django 5.2.9 on 2026-01-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory', '0031_alter_hardwarelifecycle_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='vendor_instance_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
