# Generated by Django 5.2.10 on 2026-01-29 10:00

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_inventory', '0036_assetprogramcoverage_owner_contract_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwarelifecycle',
            name='announcement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hardwarelifecycle',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
    ]
