# Generated by Django 5.2.10 on 2026-02-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory', '0037_hardwarelifecycle_announcement_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='support_reason',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='support_source',
            field=models.CharField(default='manual', max_length=30),
        ),
        migrations.AddField(
            model_name='asset',
            name='support_state',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='asset',
            name='support_validated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
