# Generated by Django 5.2.12 on 2026-04-07 12:45

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0226_modulebay_rebuild_tree'),
        ('extras', '0134_owner'),
        ('netbox_inventory', '0039_assetprogramcoverage_activated_via_decision_reason_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetprogramcoverage',
            name='decision_reason',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('subscription_id', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='dcim.manufacturer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='netbox_inventory.order')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ('manufacturer', 'subscription_id'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AssetLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_licenses', to='netbox_inventory.asset')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_licenses', to='netbox_inventory.licensesku')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_licenses', to='netbox_inventory.subscription')),
            ],
            options={
                'verbose_name': 'Asset License',
                'verbose_name_plural': 'Asset Licenses',
                'ordering': ('asset', 'sku', 'start_date'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'subscription_id'), name='netbox_inventory_subscription_unique_manufacturer_subscription_id', violation_error_message='Subscription ID must be unique per manufacturer.'),
        ),
        migrations.AddConstraint(
            model_name='assetlicense',
            constraint=models.UniqueConstraint(fields=('asset', 'sku', 'start_date'), name='netbox_inventory_assetlicense_unique_asset_sku_start', violation_error_message='An asset license record already exists for this asset, SKU, and start date.'),
        ),
    ]
