# Generated by Django 6.0.6 on 2026-07-05 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_inventory', '0045_installedatlocation_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlicense',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_licenses', to='netbox_inventory.subscription'),
        ),
        migrations.AlterField(
            model_name='assetlicense',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetlicense',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_licenses', to='netbox_inventory.order'),
        ),
        migrations.AddField(
            model_name='assetlicense',
            name='license_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='licensesku',
            name='renewal_budget_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
